### ISSUE TITLE
Texplay 4.4 does not compile on Windows - Ruby 1.9.3

### ISSUE THREAD

**Issue by burtlo** [banister/texplay#26]
Attempted to build this against commit 22ff506. It fails.

```
PS C:\source> git clone git@github.com:banister/texplay.git
PS C:\source> cd texplay
PS C:\source> git checkout 22ff506
PS C:\source\texplay> rake compile:texplay
Temporarily enhancing PATH to include DevKit...
cd tmp/i386-mingw32/texplay/1.9.3
make
linking shared-object texplay/texplay.so
bindings.o: In function `m_clone_image':
C:\source\texplay\tmp\i386-mingw32\texplay\1.9.3/../../../../ext/texplay/bindings.c:311: undefined reference to `rb_obj_reveal'
collect2: ld returned 1 exit status
make: *** [texplay.so] Error 1
rake aborted!
Command failed with status (2): [make...]

Tasks: TOP => compile:texplay => compile:texplay:i386-mingw32 => copy:texplay:i386-mingw32:1.9.3 => tmp/i386-mingw32/texplay/1.9.3/texplay.so
(See full trace by running task with --trace)
```
