### ISSUE TITLE
Fails to install on Ruby 1.9.3-p0 (OS X Lion)

### ISSUE THREAD

**Issue by semaperepelitsa** [banister/texplay#16]
Here is the install log:

```
/Users/sema/.rbenv/versions/1.9.3-p0/bin/ruby extconf.rb
creating Makefile

make
compiling actions.c
actions.c: In function ‘line_do_action’:
actions.c:52: warning: passing argument 2 of ‘has_optional_hash_arg’ discards qualifiers from pointer target type
actions.c:53: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:55: warning: passing argument 2 of ‘has_optional_hash_arg’ discards qualifiers from pointer target type
actions.c:56: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:64: warning: passing argument 2 of ‘has_optional_hash_arg’ discards qualifiers from pointer target type
actions.c:65: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:69: warning: passing argument 2 of ‘has_optional_hash_arg’ discards qualifiers from pointer target type
actions.c:70: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:113: warning: passing argument 2 of ‘set_hash_value’ discards qualifiers from pointer target type
actions.c:141: warning: passing argument 2 of ‘set_hash_value’ discards qualifiers from pointer target type
actions.c:166: warning: passing argument 2 of ‘set_hash_value’ discards qualifiers from pointer target type
actions.c: In function ‘polyline_do_action’:
actions.c:230: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:230: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:244: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c:259: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c: In function ‘ngon_do_action’:
actions.c:297: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:298: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:307: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:308: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:308: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c:313: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c:314: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c:317: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c:318: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c: In function ‘rect_do_action’:
actions.c:349: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:349: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:353: warning: passing argument 2 of ‘delete_from_hash’ discards qualifiers from pointer target type
actions.c:355: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:356: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c: In function ‘circle_do_action’:
actions.c:404: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:404: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:409: warning: passing argument 2 of ‘delete_from_hash’ discards qualifiers from pointer target type
actions.c: In function ‘glow_fill_do_action’:
actions.c:625: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c: In function ‘bezier_point’:
actions.c:781: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c:782: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c: In function ‘bezier_do_action’:
actions.c:789: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c:800: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c:813: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:813: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:821: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:822: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:824: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c:834: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c:848: warning: implicit conversion shortens 64-bit value into a 32-bit value
actions.c: In function ‘splice_do_action’:
actions.c:958: warning: passing argument 2 of ‘has_optional_hash_arg’ discards qualifiers from pointer target type
actions.c:959: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c:963: warning: passing argument 2 of ‘has_optional_hash_arg’ discards qualifiers from pointer target type
actions.c:964: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
actions.c: In function ‘line_do_action’:
actions.c:49: warning: ‘trace_color.alpha’ may be used uninitialized in this function
actions.c:49: warning: ‘trace_color.blue’ may be used uninitialized in this function
actions.c:49: warning: ‘trace_color.green’ may be used uninitialized in this function
actions.c:49: warning: ‘trace_color.red’ may be used uninitialized in this function
compiling bindings.c
bindings.c: In function ‘parse_sync_mode’:
bindings.c:168: warning: passing argument 1 of ‘string2sym’ discards qualifiers from pointer target type
bindings.c:170: warning: passing argument 1 of ‘string2sym’ discards qualifiers from pointer target type
bindings.c:172: warning: passing argument 1 of ‘string2sym’ discards qualifiers from pointer target type
bindings.c: In function ‘m_paint’:
bindings.c:203: warning: passing argument 2 of ‘has_optional_hash_arg’ discards qualifiers from pointer target type
bindings.c:204: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
bindings.c:205: warning: implicit conversion shortens 64-bit value into a 32-bit value
bindings.c: In function ‘m_to_blob’:
bindings.c:387: warning: ISO C90 forbids mixed declarations and code
bindings.c:392: warning: ISO C90 forbids mixed declarations and code
bindings.c: In function ‘m_getpixel’:
bindings.c:423: warning: passing argument 1 of ‘string2sym’ discards qualifiers from pointer target type
bindings.c:423: warning: passing argument 2 of ‘hash_value_is’ discards qualifiers from pointer target type
bindings.c: In function ‘m_flood_fill’:
bindings.c:517: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
bindings.c:519: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
bindings.c: In function ‘m_line’:
bindings.c:573: warning: passing argument 1 of ‘string2sym’ discards qualifiers from pointer target type
bindings.c:573: warning: passing argument 2 of ‘hash_value_is’ discards qualifiers from pointer target type
bindings.c:580: warning: passing argument 2 of ‘has_optional_hash_arg’ discards qualifiers from pointer target type
bindings.c: In function ‘m_splice’:
bindings.c:725: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
bindings.c:726: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
bindings.c: In function ‘m_each’:
bindings.c:900: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
bindings.c:901: warning: passing argument 2 of ‘get_from_hash’ discards qualifiers from pointer target type
compiling cache.c
compiling gen_eval.c
gen_eval.c: In function ‘rb_gen_eval’:
gen_eval.c:126: warning: implicit declaration of function ‘RCLASS_IV_TBL’
gen_eval.c:126: error: lvalue required as left operand of assignment
gen_eval.c:132: warning: cast to pointer from integer of different size
gen_eval.c:132: error: lvalue required as left operand of assignment
gen_eval.c:174: error: lvalue required as left operand of assignment
make: *** [gen_eval.o] Error 1
```

It works fine with 1.9.2-p290 though.
