### ISSUE TITLE
Texplay fails to install under Ruby 2.1

### ISSUE THREAD

**Issue by cyberarm** [banister/texplay#22]
Building native extensions.  This could take a while...
ERROR:  Error installing texplay-0.4.3.gem:
    ERROR: Failed to build gem native extension.

```
/home/cyberarm/.rvm/rubies/ruby-2.1.0/bin/ruby extconf.rb
```

checking for main() in -lglut... yes
checking for main() in -lGL... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling texplay.c
In file included from texplay.c:9:0:
texplay.h:41:3: error: ‘sync’ redeclared as different kind of symbol
/usr/include/unistd.h:997:13: note: previous declaration of ‘sync’ was here
make: **\* [texplay.o] Error 1

make failed, exit code 2

**Comment by lobo-tuerto** [comment]
Getting this error on Ubuntu 15.04, Ruby 2.2.2p95 with rbenv:

```
$ gem install texplay
Building native extensions.  This could take a while...
ERROR:  Error installing texplay:
    ERROR: Failed to build gem native extension.

    /home/someone/.rbenv/versions/2.2.2/bin/ruby -r ./siteconf20150725-9310-fouvdd.rb extconf.rb
checking for main() in -lglut... yes
checking for main() in -lGL... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling cache.c
In file included from cache.c:12:0:
texplay.h:41:3: error: ‘sync’ redeclared as different kind of symbol
 } sync;
   ^
In file included from /home/someone/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/defines.h:57:0,
                 from /home/someone/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/ruby.h:29,
                 from /home/someone/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby.h:33,
                 from cache.c:3:
/usr/include/unistd.h:972:13: note: previous declaration of ‘sync’ was here
 extern void sync (void) __THROW;
             ^
Makefile:237: recipe for target 'cache.o' failed
make: *** [cache.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/someone/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/texplay-0.4.3 for inspection.
Results logged to /home/someone/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/texplay-0.4.3/gem_make.out
```

**Comment by ghost** [comment]
You should use the ruby -1.9.1 or -1.8.6!For that,please execute rvm default 1.9.1 or rvm default 1.8.6 in command line.After this,execute sudo gem install texplay.Hopefully,you will have already installed texplay! @lobo-tuerto

**Comment by lobo-tuerto** [comment]
@dukuikui Thanks for the info, hope this gets migrated to Ruby 2.x+ !

Working with Ruby 1.8.6 (or Ruby < 2 for that matter) is a no-no for the moment.

**Comment by timnew** [comment]
Failed to build on `ruby-2.2.3`

```
[rtanque] gem install texplay -v 0.4.4.pre
Building native extensions.  This could take a while...
ERROR:  Error installing texplay:
    ERROR: Failed to build gem native extension.

    /Users/timnew/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20160422-84716-gh2jn2.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling actions.c
actions.c:12:11: fatal error: 'GL/glut.h' file not found
# include <GL/glut.h>
          ^
1 error generated.
make: *** [actions.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/timnew/.rvm/gems/ruby-2.2.3/gems/texplay-0.4.4.pre for inspection.
Results logged to /Users/timnew/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/texplay-0.4.4.pre/gem_make.out
```

Is this because of `gosu`? I'm using  `gosu (0.10.6)`
